default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: labase_food_development

test:
  <<: *default
  database: labase_food_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cable:
  development:
    <<: *default
    database: labase_food_cable_development
  test:
    <<: *default
    database: labase_food_cable_test
  production:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['DATABASE_URL'] %>

queue:
  development:
    <<: *default
    database: labase_food_queue_development
  test:
    <<: *default
    database: labase_food_queue_test
  production:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['DATABASE_URL'] %>

cache:
  development:
    <<: *default
    database: labase_food_cache_development
  test:
    <<: *default
    database: labase_food_cache_test
  production:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['DATABASE_URL'] %>